from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class ScoreCard(QtWidgets.QWidget):
    def __init__(self):
        super(ScoreCard, self).__init__()
        self.init_ui()


    def init_ui(self):
        self.resize(721, 70)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setStyleSheet("background-color: rgb(70, 57, 63);\n"
"color: rgb(255, 255, 255);\n"
"font: 63 8pt \"Torus Pro SemiBold\";")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout_2.setContentsMargins(11, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 11, 20, 11)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.beatmap_title = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beatmap_title.sizePolicy().hasHeightForWidth())
        self.beatmap_title.setSizePolicy(sizePolicy)
        self.beatmap_title.setStyleSheet("font: 63 10pt \"Torus Pro SemiBold\";")
        self.beatmap_title.setObjectName("beatmap_title")
        self.verticalLayout.addWidget(self.beatmap_title)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(14)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.beatmap_difficulty = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beatmap_difficulty.sizePolicy().hasHeightForWidth())
        self.beatmap_difficulty.setSizePolicy(sizePolicy)
        self.beatmap_difficulty.setStyleSheet("color: rgb(255, 170, 0);")
        self.beatmap_difficulty.setObjectName("beatmap_difficulty")
        self.horizontalLayout_3.addWidget(self.beatmap_difficulty)
        self.time_elapsed = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_elapsed.sizePolicy().hasHeightForWidth())
        self.time_elapsed.setSizePolicy(sizePolicy)
        self.time_elapsed.setStyleSheet("color: rgb(170, 170, 255);")
        self.time_elapsed.setObjectName("time_elapsed")
        self.horizontalLayout_3.addWidget(self.time_elapsed)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.mods = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mods.sizePolicy().hasHeightForWidth())
        self.mods.setSizePolicy(sizePolicy)
        self.mods.setObjectName("mods")
        self.horizontalLayout.addWidget(self.mods)
        self.play_accuracy = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_accuracy.sizePolicy().hasHeightForWidth())
        self.play_accuracy.setSizePolicy(sizePolicy)
        self.play_accuracy.setStyleSheet("color: rgb(255, 170, 0);")
        self.play_accuracy.setObjectName("play_accuracy")
        self.horizontalLayout.addWidget(self.play_accuracy)
        self.full_pp = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.full_pp.sizePolicy().hasHeightForWidth())
        self.full_pp.setSizePolicy(sizePolicy)
        self.full_pp.setObjectName("full_pp")
        self.horizontalLayout.addWidget(self.full_pp)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.frame = QtWidgets.QFrame(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background-color: rgb(56, 46, 50);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.weighted_pp = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weighted_pp.sizePolicy().hasHeightForWidth())
        self.weighted_pp.setSizePolicy(sizePolicy)
        self.weighted_pp.setStyleSheet("color: rgb(237, 97, 160);")
        self.weighted_pp.setObjectName("weighted_pp")
        self.horizontalLayout_4.addWidget(self.weighted_pp)
        self.horizontalLayout_2.addWidget(self.frame)

        self.beatmap_title.setText("Lorem Ipsum (TV Size)")
        self.beatmap_difficulty.setText("Hard")
        self.time_elapsed.setText("2 Hours Ago")
        self.mods.setText("HDDT")
        self.play_accuracy.setText("98.75%")
        self.full_pp.setText("128 pp")
        self.weighted_pp.setText("64 pp")


        


if __name__ == "__main__":
    
    app = QtWidgets.QApplication(sys.argv)
    ui = ScoreCard()
    sys.exit(app.exec_())
